/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Util.Utilidades;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Controlador.Controlador;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JDialog;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author Antonio Martinez Diaz
 */





public class TablaVentas extends javax.swing.JFrame implements MouseListener, TableModelListener{

    private ModeloTabla modelo;
    private static ArrayList<String> titulosList;
    private static String busqueda;
    
    private static int campoBusqueda;
    private DefaultTableModel modeleloResultado;
    
    
    /**
     * Creates new form TablaVentas
     */
    public TablaVentas() {
        initComponents();
         construirTabla();
        tVentas.addMouseListener(this);
        tVentas.getModel().addTableModelListener(this);
       // busqueda = "";
       // campoBusqueda = Utilidades.NOMBRE;
       // modeleloResultado = (DefaultTableModel) tablaResultado.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
      public void construirTabla() {
        titulosList = new ArrayList<>();
        titulosList.add("Id");
        titulosList.add("Fecha");
        titulosList.add("Precio");
        titulosList.add("");
        titulosList.add("");
        titulosList.add("");
        titulosList.add("");

        String titulos[] = new String[titulosList.size()];
        for (int i = 0; i < titulos.length; i++) {
            titulos[i] = titulosList.get(i);
        }

        Object[][] data = obtenerMatrizDatos(titulosList);
        construirTabla(titulos, data);
    }

      
      
       private Object[][] obtenerMatrizDatos(ArrayList<String> titulosList) {
        String informacion[][] = new String[Controlador.devolverVentas().size()][titulosList.size()];
        for (int x = 0; x < informacion.length; x++) {
            informacion[x][Utilidades.ID] = Controlador.obtenerCampoMo("id", x);
            informacion[x][Utilidades.FECHA] = Controlador.obtenerCampoMo("fecha", x);
            informacion[x][Utilidades.PRECIO] = Controlador.obtenerCampoMo("precio", x);
            informacion[x][Utilidades.COCHE] = "COCHE";
        }
        return informacion;
    }
      
      
    public void restaurarEscucha() {
        tVentas.getModel().removeTableModelListener(this);
        tVentas.getModel().addTableModelListener(this);
    }
    
    
      private void construirTabla(String[] titulos, Object[][] data) {
        modelo = new ModeloTabla(data, titulos);
        tVentas.setModel(modelo);
        tVentas.getColumnModel().getColumn(Utilidades.COCHE).setCellRenderer(new GestionCeldas("icono")); 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tVentas;
    // End of variables declaration//GEN-END:variables

    
    
     private int idTabla(int fila) {
        String id = (String) modelo.getValueAt(fila, 0);
        int Id = Integer.parseInt(id);
        return Id;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        int fila = tVentas.rowAtPoint(e.getPoint());
        int columna = tVentas.columnAtPoint(e.getPoint());

        if (columna == Utilidades.COCHE) {
            int id = idTabla(fila);
            JDialog frame = new JDialog(this, "Editar Coche", true);
            frame.setLocation(this.getX(), this.getY());
            FormularioCoche f = new  FormularioCoche(id);
            frame.getContentPane().add(f);
            frame.pack();
            frame.setVisible(true);
            construirTabla();
            restaurarEscucha();

        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
       
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }
    
    
    
     private void actualizaCelda(TableModelEvent e) {
        String id = (String) modelo.getValueAt(e.getFirstRow(), 0);
        System.out.println(modelo.getValueAt(e.getFirstRow(), 0));
        int Id = Integer.parseInt(id);
        String cambio = (String) modelo.getValueAt(e.getFirstRow(), e.getColumn());
        Controlador.actualizarMo(Id, (Integer.valueOf(e.getColumn())), cambio);
    }

    @Override
    public void tableChanged(TableModelEvent e) {        
        if (e.getColumn() == Utilidades.FECHA) {
           // if (Utilidades.esSoloLetras(Cambio)) {
                actualizaCelda(e);
                
            /*  } else {
                errorTextoDialog();
                construirTabla();
                restaurarEscucha();
            }*/
        }else if(e.getColumn() == Utilidades.PRECIO){
             actualizaCelda(e);
        }
        
        
        
        
        
        
        
        
        
        
    }
}
